name = "gingeleski-hugo-theme"
license = "MIT"
licenselink = "https://github.com/gingeleski/gingeleski-hugo-theme/blob/master/LICENSE"
description = "The custom theme developed for and by Randy Gingeleski."
tags = ["blog", "dark", "light"]
features = ["darkmode"]
min_version = "0.54.0"

[author]
  name = "Randy Gingeleski"
  homepage = "https://gingeleski.com"
  repo = "https://github.com/gingeleski/gingeleski-hugo-theme"

[original]
  name = "Casper default theme for Ghost"
  homepage = "https://ghost.org"
  repo = "https://github.com/TryGhost/Casper"
